 version: '3.8'
 services:
   database:
     image: postgres:15
     restart: always
     ports:
       - '5432:5432'
     volumes:
       - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
     env_file:
       - ./.env
     healthcheck:
       test: ["CMD-SHELL", "pg_isready -U postgres"]
       interval: 10s
       timeout: 5s
       retries: 5

   backend:
     image: backend
     build:
       context: ./backend
       dockerfile: Dockerfile.dev
     ports:
       - '8080:8080'
     volumes:
       - ./backend:/app
     env_file:
       - ./.env
     depends_on:
       - database

 volumes:
   database:
     driver: local
