version: '3.8'
services:
  database:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  application:
    image: application
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    volumes:
      - ./app:/app # Mounts the application directory to /app in the container
    env_file:
      - ./.env
    depends_on:
      - database
    working_dir: /app # Sets the working directory to /app in the container

volumes:
  database:
    driver: local

