version: '3.8'
services:
  database:
    image: postgres:15
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  ## Go Server
  backend:
    image: backend
    build:
      context: src/backend
      dockerfile: Dockerfile.dev
    ports:
      - '8080:8080'
    volumes:
      - ./src/backend:/app
    env_file:
      - ./.env
    depends_on:
      - database

  frontend-react:
   image: frontend-react
   build:
     context: src/frontend/react-app
     dockerfile: Dockerfile.dev
   ports:
     - '3000:3000'
   volumes:
     - ./src/frontend/react-app:/app
     - /app/node_modules
   env_file:
     - ./.env
   depends_on:
     - database
     - backend

volumes:
  database:
    driver: local

